[toolchain]
anchor_version = "0.31.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_arbitrage_dev = "AhG6TxE9hBnYGjLzkT8FkhZ763CEAo5r8MjzxwrXhfoh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/solana-arbitrage-dev/scripts/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
